# Generated by Django 3.1 on 2020-12-27 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL),
        ),
    ]
