# Generated by Django 3.1 on 2020-12-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201227_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.me'),
        ),
    ]
