# Generated by Django 3.1 on 2020-12-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201228_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='score',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
