# Generated by Django 3.1 on 2020-12-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201228_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
