# Generated by Django 3.1 on 2020-12-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201228_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='score',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
