# Generated by Django 3.1 on 2020-12-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_towatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towatch',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
