# Generated by Django 3.1 on 2020-12-28 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_auto_20201228_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towatch',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='towatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
