# Generated by Django 3.1 on 2020-12-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_towatch_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towatch',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
