# Generated by Django 3.1 on 2020-12-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20201228_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towatch',
            name='score',
        ),
    ]
